#pragma once

/**
 * @brief Compiled-in curated public-suffix rules for registrable-domain tests.
 * @author Alex (https://github.com/lextpf)
 * @ingroup Utilities
 *
 * GENERATED FILE. scripts/generate_public_suffix_table.py writes it from
 * scripts/public_suffixes.txt. A hand edit is lost on the next run of the
 * generator. To change a rule, edit the rule source; to change the prose or
 * the layout, edit the generator template.
 *
 * The table is a curated subset of the Mozilla Public Suffix List, not the
 * whole list. seal never fetches the list at run time, so this snapshot is the
 * only rule source that seal::url::detail::publicSuffixView() reads.
 *
 * The rules are split by match kind, because each kind is applied differently:
 *  - @ref kExactPublicSuffixes - the rule is itself a public suffix. The
 *    longest dot-aligned match, counted in labels, wins.
 *  - @ref kWildcardPublicSuffixes - the base of a `*.<base>` rule. A match
 *    consumes exactly one more label to the left of the base.
 *  - @ref kPublicSuffixExceptions - the body of a `!<rule>` line. An exception
 *    outranks both other kinds, and the public suffix it yields is the rule
 *    without its left-most label.
 *
 * A host that matches no rule falls back to its last label. That is the
 * implicit `*` rule of the PSL algorithm.
 *
 * Every array is sorted, lower-case and ASCII; the generator rejects a rule
 * that is not punycode-encoded. Lookup scans the three arrays linearly.
 */

#include <array>
#include <string_view>

namespace seal::url::detail
{

/// Snapshot identity of the curated list, as `YYYY-MM-DD_HH-MM-SS_UTC`.
inline constexpr std::string_view kSuffixTableSnapshot = "2026-07-25_14-20-03_UTC";

/// Upstream PSL commit that the curated snapshot was reviewed against.
inline constexpr std::string_view kSuffixTableCommit = "e1b8015c3b2f0f4f8c18659c2480fc1a22c07b20";

/// Rules that are themselves public suffixes.
inline constexpr std::array<std::string_view, 341> kExactPublicSuffixes = {{
    "ac.at",
    "ac.bd",
    "ac.cn",
    "ac.id",
    "ac.il",
    "ac.in",
    "ac.jp",
    "ac.ke",
    "ac.kr",
    "ac.nz",
    "ac.th",
    "ac.uk",
    "ac.vn",
    "appspot.com",
    "asn.au",
    "azurestaticapps.net",
    "azurewebsites.net",
    "bel.tr",
    "biz.az",
    "biz.id",
    "biz.pk",
    "biz.tr",
    "blogspot.com",
    "cloudapp.azure.com",
    "cloudflare.app",
    "cloudfront.net",
    "cloudfunctions.net",
    "co.ag",
    "co.am",
    "co.ao",
    "co.at",
    "co.az",
    "co.bd",
    "co.bi",
    "co.bw",
    "co.ck",
    "co.cr",
    "co.id",
    "co.il",
    "co.in",
    "co.jp",
    "co.ke",
    "co.kr",
    "co.ls",
    "co.ma",
    "co.mz",
    "co.nz",
    "co.th",
    "co.tz",
    "co.ug",
    "co.uk",
    "co.uz",
    "co.ve",
    "co.za",
    "codesandbox.io",
    "com.ac",
    "com.af",
    "com.ag",
    "com.ai",
    "com.al",
    "com.ar",
    "com.au",
    "com.az",
    "com.ba",
    "com.bb",
    "com.bd",
    "com.bh",
    "com.bo",
    "com.br",
    "com.bz",
    "com.cn",
    "com.co",
    "com.cy",
    "com.do",
    "com.ec",
    "com.eg",
    "com.es",
    "com.et",
    "com.fj",
    "com.ge",
    "com.gh",
    "com.gt",
    "com.hk",
    "com.jm",
    "com.kh",
    "com.kw",
    "com.lb",
    "com.ly",
    "com.mm",
    "com.mt",
    "com.mx",
    "com.my",
    "com.na",
    "com.ng",
    "com.ni",
    "com.np",
    "com.om",
    "com.pa",
    "com.pe",
    "com.ph",
    "com.pk",
    "com.pl",
    "com.pr",
    "com.py",
    "com.qa",
    "com.ro",
    "com.sa",
    "com.sg",
    "com.sv",
    "com.tr",
    "com.tw",
    "com.ua",
    "com.uy",
    "com.ve",
    "com.vn",
    "com.ye",
    "edu.ar",
    "edu.au",
    "edu.bd",
    "edu.br",
    "edu.cn",
    "edu.co",
    "edu.do",
    "edu.ec",
    "edu.eg",
    "edu.hk",
    "edu.in",
    "edu.mx",
    "edu.my",
    "edu.ng",
    "edu.nz",
    "edu.pe",
    "edu.ph",
    "edu.pk",
    "edu.sa",
    "edu.sg",
    "edu.tr",
    "edu.tw",
    "edu.ua",
    "edu.uy",
    "edu.vn",
    "firebaseapp.com",
    "firm.in",
    "fly.dev",
    "geek.nz",
    "gen.in",
    "gen.nz",
    "gen.tr",
    "gitbook.io",
    "github.app",
    "github.io",
    "githubpreview.dev",
    "githubusercontent.com",
    "glitch.me",
    "go.id",
    "go.jp",
    "go.ke",
    "go.kr",
    "go.th",
    "gob.ar",
    "gob.mx",
    "gob.pe",
    "gob.sv",
    "gov.ar",
    "gov.au",
    "gov.bd",
    "gov.br",
    "gov.cn",
    "gov.co",
    "gov.cy",
    "gov.do",
    "gov.ec",
    "gov.eg",
    "gov.hk",
    "gov.il",
    "gov.in",
    "gov.jm",
    "gov.lk",
    "gov.my",
    "gov.ng",
    "gov.ph",
    "gov.pk",
    "gov.sa",
    "gov.sg",
    "gov.tr",
    "gov.tw",
    "gov.ua",
    "gov.uk",
    "gov.vn",
    "gov.za",
    "govt.nz",
    "gr.jp",
    "herokuapp.com",
    "herokussl.com",
    "hs.kr",
    "id.au",
    "idv.hk",
    "idv.tw",
    "in.th",
    "in.ua",
    "ind.in",
    "info.ke",
    "info.tr",
    "iwi.nz",
    "lg.jp",
    "maori.nz",
    "me.ke",
    "me.uk",
    "med.sa",
    "mil.bd",
    "mil.br",
    "mil.co",
    "mil.in",
    "mil.kr",
    "mil.my",
    "mil.ph",
    "mil.tr",
    "mobi.ke",
    "mobi.ng",
    "ms.kr",
    "muni.il",
    "myshopify.com",
    "name.my",
    "name.ng",
    "name.tr",
    "ne.jp",
    "ne.kr",
    "net.ar",
    "net.au",
    "net.bd",
    "net.br",
    "net.cn",
    "net.co",
    "net.do",
    "net.eg",
    "net.hk",
    "net.id",
    "net.il",
    "net.in",
    "net.ke",
    "net.kr",
    "net.mx",
    "net.my",
    "net.ng",
    "net.nz",
    "net.pe",
    "net.ph",
    "net.pk",
    "net.sa",
    "net.sg",
    "net.th",
    "net.tr",
    "net.tw",
    "net.ua",
    "net.uy",
    "net.ve",
    "net.vn",
    "net.za",
    "netlify.app",
    "netlify.com",
    "nhs.uk",
    "nom.co",
    "nom.es",
    "now.sh",
    "onrender.com",
    "or.id",
    "or.jp",
    "or.ke",
    "or.kr",
    "or.th",
    "org.ar",
    "org.au",
    "org.bd",
    "org.br",
    "org.cn",
    "org.co",
    "org.do",
    "org.eg",
    "org.es",
    "org.hk",
    "org.il",
    "org.in",
    "org.ke",
    "org.kr",
    "org.mx",
    "org.my",
    "org.ng",
    "org.nz",
    "org.pe",
    "org.ph",
    "org.pk",
    "org.sa",
    "org.sg",
    "org.tr",
    "org.tw",
    "org.ua",
    "org.uk",
    "org.uy",
    "org.ve",
    "org.vn",
    "org.za",
    "pages.dev",
    "pe.kr",
    "per.sg",
    "plc.uk",
    "police.uk",
    "pub.sa",
    "pythonanywhere.com",
    "r2.dev",
    "re.kr",
    "readthedocs.io",
    "repl.co",
    "replit.app",
    "res.in",
    "s3-website-us-east-1.amazonaws.com",
    "s3-website-us-west-1.amazonaws.com",
    "s3-website-us-west-2.amazonaws.com",
    "s3.amazonaws.com",
    "sc.ke",
    "sc.kr",
    "sch.id",
    "sch.ng",
    "sch.sa",
    "sch.uk",
    "school.nz",
    "school.za",
    "squarespace.com",
    "surge.sh",
    "trycloudflare.com",
    "vercel.app",
    "vercel.dev",
    "vercel.run",
    "vusercontent.net",
    "web.app",
    "web.id",
    "web.pk",
    "web.tr",
    "weebly.com",
    "wixsite.com",
    "wordpress.com",
    "workers.dev",
}};

/// Bases of `*.<base>` rules; a match takes one more label.
inline constexpr std::array<std::string_view, 1> kWildcardPublicSuffixes = {{
    "ck",
}};

/// Bodies of `!<rule>` lines; each one cancels a wildcard match.
inline constexpr std::array<std::string_view, 1> kPublicSuffixExceptions = {{
    "www.ck",
}};

}  // namespace seal::url::detail
